version: '3.8'
services:
  mongp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongp_db

  mongp_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: monGP
      MYSQL_USER: phpmyadmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33060:3306
